# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: 
  pull_request:
    branches: ["main"]

# List of jobs
jobs:
  storybook:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    outputs:
      status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - name: publish to chromatic
        id: chromatic
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: comment PR
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "🚀storybook: ${{ steps.chromatic.outputs.storybookUrl }}"